// <auto-generated />
using Barlangok.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barlangok.Migrations
{
    [DbContext(typeof(BarlangokDb))]
    [Migration("20250930062019_sqlite.local_migration_799")]
    partial class sqlitelocal_migration_799
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");
#pragma warning restore 612, 618
        }
    }
}
